# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Инженерная
email: team@engnr.io
description: > # this means to ignore newlines until "baseurl:"
  Разрабатываем приложения для настольных компьютеров и встраиваемых устройств.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://engnr.io" # the base hostname & protocol for your site
phone:
  link: "+74951111111"
  text: "495 111 11 11"

integrations:
  google_analytics:
    id: 'UA-90938007-1'
  yandex_metrika:
    id: 42441234
  intercom:
    app_id: "gz5jgvs3"


theme: engnr-theme
gems:
  - jekyll-redirect-from

assets:
  semantic: /assets/semantic-css
  semantic-components: /assets/semantic-css/components
  css: /assets/css
  js: /assets/js


sass:
  style: compressed

permalink: /blog/:title/

# Build settings
markdown: kramdown
exclude:
  - node_modules

collections:
  events:
    output: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      navigation_group: blog
  - scope:
      path: ""
      type: events
    values:
      permalink: /:collection/:title/
      navigation_group: events
