backend:
  name: github
  repo: engnr/engnr.io
  branch: master

media_folder: "uploads"
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Блог
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - { label: "Категория", name: "category", widget: "string"}
    - { label: "Автор", name: "author", widget: "string"}
    - { label: "Заголовок", name: "title", widget: "string"}
    - { label: "Статья", name: "body", widget: "markdown"}
  - name: events
    label: События
    folder: _events
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - { label: "Заголовок", name: "title", widget: "string" }
    - { label: "Описание", name: "description", widget: "text" }
    - { label: "Место проведения", name: "location", widget: "string" }
    - { label: "Дата начала", name: "start_date", widget: "datetime" }
    - { label: "Дата завершения", name: "end_date", widget: "datetime" }
    - { label: "Тренер", name: "coach", widget: "string" }
    - { label: "Цена", name: "price", widget: "number" }
    - { label: "Статья", name: "body", widget: "markdown" }
  - name: jobs
    label: Вакансии
    folder: _jobs
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - { label: "Заголовок", name: "title", widget: "string" }
    - { label: "Тип работы", name: "job_type", widget: "select", options: ["", Удалённая работа"], default: "", required: false }
    - { label: "Дата открытия", name: "open_date", widget: "datetime", format: "YYYY-MM-DD" }
    - { label: "Дата закрытия", name: "close_date", widget: "datetime", format: "YYYY-MM-DD", required: false }
    - { label: "Навыки", name: "skills", widget: "list", required: false }
    - { label: "Статья", name: "body", widget: "markdown" }
  - name: settings
    label: Настройки
    editor:
      preview: false
    files:
      - name: "general"
        label: Настройки сайта
        file: "_data/settings.yml"
        description: Основные настройки сайта
        fields:
          - name: navigation
            label: Навигация
            widget: list
            fields:
              - { label: "Заголовок", name: "title", widget: "string" }
              - { label: "Ссылка", name: "url", widget: "string" }


