backend:
  name: github
  repo: engnr/engnr.io
  branch: master

media_folder: "uploads"
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Category", name: "category", widget: "string"}
    - {label: "Author", name: "author", widget: "string"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site settings"
        file: "_data/settings.yml"
        description: "General Site Settings"
        fields:
          - name: navigation
            label: Navigation
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }


